adding docker-compose and all

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,13 +1,36 @@
-FROM node:18-alpine
+FROM node:18-alpine AS deps
+RUN apk add --no-cache libc6-compat
+WORKDIR /app
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+FROM node:18-alpine AS prod
+
+ARG BASEURL
+ENV BASEURL $BASEURL
+
+RUN apk add nginx
 
 WORKDIR /app
 
-COPY package.json
+COPY --from=deps /app/node_modules ./node_modules
 
-RUN npm install
+COPY nginx.conf /etc/nginx/http.d/default.conf
 
 COPY . .
 
-EXPOSE 3000
 
-CMD ["npm", "run", "dev"]
+RUN sed -i "s|http://localhost:5000|$BASEURL|" src/api/constant.js
+
+EXPOSE 8080
+
+#CMD ["npm", "run", "dev"]
+
+ENTRYPOINT ["./entrypoint.sh"]
